// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJmHTg61gGt_sj-4ts3yUk2YBMM2cBqnY',
    appId: '1:566026126040:web:cd1f3a709563938d984dad',
    messagingSenderId: '566026126040',
    projectId: 'prospect-pulse',
    authDomain: 'prospect-pulse.firebaseapp.com',
    storageBucket: 'prospect-pulse.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYsvGMbgWJQX0j-Gt6Lcq2_Or5SU3QHp4',
    appId: '1:566026126040:android:9158fbe9f36c8e8e984dad',
    messagingSenderId: '566026126040',
    projectId: 'prospect-pulse',
    storageBucket: 'prospect-pulse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJvOXXHTMRPGV9ZKPLyTepXFASAfwkRXc',
    appId: '1:566026126040:ios:435e6e8fd7c62f8c984dad',
    messagingSenderId: '566026126040',
    projectId: 'prospect-pulse',
    storageBucket: 'prospect-pulse.appspot.com',
    iosBundleId: 'com.example.prospectPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJvOXXHTMRPGV9ZKPLyTepXFASAfwkRXc',
    appId: '1:566026126040:ios:2c2f2583671d203b984dad',
    messagingSenderId: '566026126040',
    projectId: 'prospect-pulse',
    storageBucket: 'prospect-pulse.appspot.com',
    iosBundleId: 'com.example.prospectPulse.RunnerTests',
  );
}
